package com.example.lesson11;

import android.content.Context;

import java.util.ArrayList;

/**
 * Created with IntelliJ IDEA.
 * User: javlon
 * Date: 02.02.14
 * Time: 20:18
 * To change this template use File | Settings | File Templates.
 */
public class WordsCollection {
    private String query;
    private Context context;
    public WordsCollection(Context context, String query) {
        this.query = query;
        this.context = context;
    }
    public ArrayList<Word> searching(){
        ArrayList<Word> ans = new ArrayList<Word>();
        if(query.equals("Одежда") || query.equals("Kiyim")){
            Word word = new Word();
            word.setName("pants");
            word.setRussian("Брюки");
            word.setUzbek("Shim");
            ans.add(word);
            word = new Word();


            word.setName("boots");
            word.setRussian("Обувь");
            word.setUzbek("Oyoq-kiyim");
            ans.add(word);
            word = new Word();
            word.setName("belt");
            word.setRussian("Ремень");
            word.setUzbek("Kamar");
            ans.add(word);
            word = new Word();

            word.setName("shirt");
            word.setRussian("Рубашка");
            word.setUzbek("Ko'ylak");
            ans.add(word);
            word = new Word();
            word.setName("skullcap");
            word.setRussian("Тюбетейка");
            word.setUzbek("Do'ppi");
            ans.add(word);
            word = new Word();
            word.setName("socks");
            word.setRussian("Носки");
            word.setUzbek("Paypoq");
            ans.add(word);
            word = new Word();
            word.setName("tie");
            word.setRussian("Галстук");
            word.setUzbek("Bo'yinboq");
            ans.add(word);
            word = new Word();
            word.setName("shawl");
            word.setRussian("Платок");
            word.setUzbek("Ro'mol");
            ans.add(word);
            word = new Word();
            word.setName("gloves");
            word.setRussian("Перчатки");
            word.setUzbek("Qo'lqop");
            ans.add(word);
            word = new Word();
            word.setName("robe");
            word.setRussian("Халат");
            word.setUzbek("Chopon");
            ans.add(word);
        }
        if(query.equals("Фрукты")||query.equals("Mevalar")){
            Word word = new Word();
            word.setName("apple");
            word.setRussian("Яблоко");
            word.setUzbek("Olma");
            ans.add(word);
            word = new Word();
            word.setName("pear");
            word.setRussian("Груша");
            word.setUzbek("Nok");
            ans.add(word);
            word = new Word();
            word.setName("grenade");
            word.setRussian("Гранат");
            word.setUzbek("Anor");
            ans.add(word);
            word = new Word();
            word.setName("grapes");
            word.setRussian("Виноград");
            word.setUzbek("Uzum");
            ans.add(word);
            word = new Word();
            word.setName("peach");
            word.setRussian("Персик");
            word.setUzbek("Shaftoli");
            ans.add(word);
            word = new Word();
            word.setName("apricot");
            word.setRussian("Абрикос");
            word.setUzbek("O'rik");
            ans.add(word);
            word = new Word();
            word.setName("cherry");
            word.setRussian("Черешние");
            word.setUzbek("Gilos");
            ans.add(word);
            word = new Word();
            word.setName("strawberry");
            word.setRussian("Клубника");
            word.setUzbek("Qulupnay");
            ans.add(word);
            word = new Word();
            word.setName("fig");
            word.setRussian("Инжир");
            word.setUzbek("Anjir");
            ans.add(word);
            word = new Word();
            word.setName("melon");
            word.setRussian("Дыня");
            word.setUzbek("Qovun");
            ans.add(word);
        }
        if(query.equals("Животные")|| query.equals("Hayvonlar")){
            Word word = new Word();
            word.setName("cow");
            word.setRussian("Корова");
            word.setUzbek("Sigir");
            ans.add(word);
            word = new Word();
            word.setName("sheep");
            word.setRussian("Баран");
            word.setUzbek("Qo'chqor");
            ans.add(word);
            word = new Word();
            word.setName("horse");
            word.setRussian("Лошадь");
            word.setUzbek("Ot");
            ans.add(word);
            word = new Word();
            word.setName("chicken");
            word.setRussian("Курица");
            word.setUzbek("Tovuq");
            ans.add(word);
            word = new Word();
            word.setName("cock");
            word.setRussian("Петух");
            word.setUzbek("Xo'roz");
            ans.add(word);
            word = new Word();
            word.setName("chickenmi");
            word.setRussian("Цыпленок");
            word.setUzbek("Jo'ja");
            ans.add(word);
            word = new Word();
            word.setName("dog");
            word.setRussian("Собака");
            word.setUzbek("It");
            ans.add(word);
            word = new Word();
            word.setName("cat");
            word.setRussian("Кошка");
            word.setUzbek("Mushuk");
            ans.add(word);
            word = new Word();
            word.setName("pigeon");
            word.setRussian("Голубь");
            word.setUzbek("Kabutar");
            ans.add(word);
            word = new Word();
            word.setName("crow");
            word.setRussian("Ворона");
            word.setUzbek("Qarg'a");
            ans.add(word);
        }
        if(query.equals("Части тела")||query.equals("Tana azolari")){
            Word word = new Word();
            word.setName("hand");
            word.setRussian("Рука");
            word.setUzbek("Qo'l");
            ans.add(word);
            word = new Word();
            word.setName("leg");
            word.setRussian("Нога");
            word.setUzbek("Oyoq");
            ans.add(word);
            word = new Word();
            word.setName("finger");
            word.setRussian("Палец");
            word.setUzbek("Barmoq");
            ans.add(word);
            word = new Word();
            word.setName("elbow");
            word.setRussian("Локтя");
            word.setUzbek("Tirsak");
            ans.add(word);
            word = new Word();
            word.setName("palm");
            word.setRussian("Ладонь");
            word.setUzbek("Panja");
            ans.add(word);
            word = new Word();
            word.setName("back");
            word.setRussian("Спина");
            word.setUzbek("Orqa");
            ans.add(word);
            word = new Word();
            word.setName("nose");
            word.setRussian("Нос");
            word.setUzbek("Burun");
            ans.add(word);
            word = new Word();
            word.setName("tongue");
            word.setRussian("Язык");
            word.setUzbek("Til");
            ans.add(word);
            word = new Word();
            word.setName("eye");
            word.setRussian("Глаза");
            word.setUzbek("Ko'z");
            ans.add(word);
            word = new Word();
            word.setName("eyebrow");
            word.setRussian("Брови");
            word.setUzbek("Qosh");
            ans.add(word);
        }
        if(query.equals("Математика")||query.equals("Matematika")){
            Word word = new Word();
            word.setName("plus");
            word.setRussian("Складывать");
            word.setUzbek("Qo'shuv");
            ans.add(word);
            word = new Word();
            word.setName("minus");
            word.setRussian("Вычитать");
            word.setUzbek("Ayirmoq");
            ans.add(word);
            word = new Word();
            word.setName("multiple");
            word.setRussian("Умножение");
            word.setUzbek("Ko'paytirmoq");
            ans.add(word);
            word = new Word();
            word.setName("division");
            word.setRussian("Деление");
            word.setUzbek("Bo'lish");
            ans.add(word);
            word = new Word();
            word.setName("sqrt");
            word.setRussian("Корень");
            word.setUzbek("Ildiz");
            ans.add(word);
            word = new Word();
            word.setName("equal");
            word.setRussian("Равно");
            word.setUzbek("Teng");
            ans.add(word);
            word = new Word();
            word.setName("zero");
            word.setRussian("Ноль");
            word.setUzbek("Nol");
            ans.add(word);
            word = new Word();
            word.setName("one");
            word.setRussian("Единица");
            word.setUzbek("Bir");
            ans.add(word);
            word = new Word();
            word.setName("seven");
            word.setRussian("Семь");
            word.setUzbek("Yetti");
            ans.add(word);
            word = new Word();
            word.setName("numbers");
            word.setRussian("Число");
            word.setUzbek("Son");
            ans.add(word);
        }
        if(query.equals("Виды спорта") || query.equals("Sport turlari")){
            Word word = new Word();
            word.setName("swimming");
            word.setRussian("Плавание");
            word.setUzbek("Suzish");
            ans.add(word);
            word = new Word();
            word.setName("fight");
            word.setRussian("Борьба");
            word.setUzbek("Kurash");
            ans.add(word);
            word = new Word();
            word.setName("run");
            word.setRussian("Бег");
            word.setUzbek("Yugurish");
            ans.add(word);
            word = new Word();
            word.setName("fixto");
            word.setRussian("Фехтование");
            word.setUzbek("Qilichbozlik");
            ans.add(word);
            word = new Word();
            word.setName("rukb");
            word.setRussian("Рукопашный бой");
            word.setUzbek("Qo'l jangi");
            ans.add(word);
            word = new Word();
            word.setName("strelba");
            word.setRussian("Стрельба из лука");
            word.setUzbek("Kamonda o'q uzish");
            ans.add(word);
            word = new Word();
            word.setName("kupkari");
            word.setRussian("Купкари");
            word.setUzbek("Ko'pkari");
            ans.add(word);
            word = new Word();
            word.setName("hockey");
            word.setRussian("Хоккей");
            word.setUzbek("Xokkey");
            ans.add(word);
            word = new Word();
            word.setName("americanfootbal");
            word.setRussian("Американский футбол");
            word.setUzbek("Amerikancha futbol");
            ans.add(word);
            word = new Word();
            word.setName("soccer");
            word.setRussian("Футбол");
            word.setUzbek("Futbol");
            ans.add(word);
        }
        if(query.equals("Цвета") || query.equals("Ranglar")){
            Word word = new Word();
            word.setName("red");
            word.setRussian("Красный");
            word.setUzbek("Qizil");
            ans.add(word);
            word = new Word();
            word.setName("blue");
            word.setRussian("Синий");
            word.setUzbek("Ko'k");
            ans.add(word);
            word = new Word();
            word.setName("white");
            word.setRussian("Белый");
            word.setUzbek("Oq");
            ans.add(word);
            word = new Word();
            word.setName("yellow");
            word.setRussian("Жёлтый");
            word.setUzbek("Sariq");
            ans.add(word);
            word = new Word();
            word.setName("green");
            word.setRussian("Зелённый");
            word.setUzbek("Yashil");
            ans.add(word);
            word = new Word();
            word.setName("orange");
            word.setRussian("Оранжевый");
            word.setUzbek("To'q sariq");
            ans.add(word);
            word = new Word();
            word.setName("black");
            word.setRussian("Черный");
            word.setUzbek("Qora");
            ans.add(word);
            word = new Word();
            word.setName("gray");
            word.setRussian("Серый");
            word.setUzbek("Kulrang");
            ans.add(word);
            word = new Word();
            word.setName("pink");
            word.setRussian("Розовый");
            word.setUzbek("Pushti rang");
            ans.add(word);
            word = new Word();
            word.setName("blueg");
            word.setRussian("Голубой");
            word.setUzbek("Havo rang");
            ans.add(word);
        }
        if(query.equals("Погода") || query.equals("Ob-havo")){
            Word word = new Word();
            word.setName("sun");
            word.setRussian("Ясно");
            word.setUzbek("Ochiq");
            ans.add(word);
            word = new Word();
            word.setName("snow");
            word.setRussian("Снег");
            word.setUzbek("Qor");
            ans.add(word);
            word = new Word();
            word.setName("rain");
            word.setRussian("Дождь");
            word.setUzbek("Yomg'ir");
            ans.add(word);
            word = new Word();
            word.setName("cloud");
            word.setRussian("Облако");
            word.setUzbek("Bulut");
            ans.add(word);
            word = new Word();
            word.setName("cloud_sun");
            word.setRussian("Переменная облачность");
            word.setUzbek("O’zgaruvchan bulut bosganlik");
            ans.add(word);
            word = new Word();
            word.setName("fog");
            word.setRussian("Туман");
            word.setUzbek("Tuman");
            ans.add(word);
            word = new Word();
            word.setName("fullmoon");
            word.setRussian("Полнолуние");
            word.setUzbek("To'lin oy");
            ans.add(word);
            word = new Word();
            word.setName("ice");
            word.setRussian("Град");
            word.setUzbek("Do'l");
            ans.add(word);
            word = new Word();
            word.setName("wind");
            word.setRussian("Ветер");
            word.setUzbek("Shamol");
            ans.add(word);
            word = new Word();
            word.setName("sunshine");
            word.setRussian("Солнечный");
            word.setUzbek("Quyoshli");
            ans.add(word);
        }
        if(query.equals("Страны")||query.equals("Davlatlar")){
            Word word = new Word();
            word.setName("china");
            word.setRussian("Китай");
            word.setUzbek("Xitoy");
            ans.add(word);
            word = new Word();
            word.setName("gb");
            word.setRussian("Великобритания");
            word.setUzbek("Buyuk Britaniya");
            ans.add(word);
            word = new Word();
            word.setName("usa");
            word.setRussian("Соединённые Штаты Америки");
            word.setUzbek("Amerika Qoʻshma Shtatlari");
            ans.add(word);
            word = new Word();
            word.setName("jar");
            word.setRussian("Южно-Африканская Республика");
            word.setUzbek("Janubiy Afrika Respublikasi");
            ans.add(word);
            word = new Word();
            word.setName("uae");
            word.setRussian("Объединённые Арабские Эмираты");
            word.setUzbek("Birlashgan Arab Amirliklari");
            ans.add(word);
            word = new Word();
            word.setName("uzbekistan");
            word.setRussian("Узбекистан");
            word.setUzbek("O'zbekiston");
            ans.add(word);
            word = new Word();
            word.setName("egypt");
            word.setRussian("Египет");
            word.setUzbek("Misr");
            ans.add(word);
            word = new Word();
            word.setName("india");
            word.setRussian("Индия");
            word.setUzbek("Hindiston");
            ans.add(word);
            word = new Word();
            word.setName("palestine");
            word.setRussian("Палестина");
            word.setUzbek("Falastin");
            ans.add(word);
            word = new Word();
            word.setName("algeria");
            word.setRussian("Алжир");
            word.setUzbek("Jazoir");
            ans.add(word);
        }
        if(query.equals("Все для дома") || query.equals("Uy jihozlari")){
            Word word = new Word();
            word.setName("dish");
            word.setRussian("Посуда");
            word.setUzbek("Idish");
            ans.add(word);
            word = new Word();
            word.setName("cupboard");
            word.setRussian("Шкаф");
            word.setUzbek("Javon");
            ans.add(word);
            word = new Word();
            word.setName("mirror");
            word.setRussian("Зеркало");
            word.setUzbek("Oyna");
            ans.add(word);
            word = new Word();
            word.setName("iron");
            word.setRussian("Утюг");
            word.setUzbek("Dazmol");
            ans.add(word);
            word = new Word();
            word.setName("scissors");
            word.setRussian("Ножница");
            word.setUzbek("Qaychi");
            ans.add(word);
            word = new Word();
            word.setName("door");
            word.setRussian("Дверь");
            word.setUzbek("Eshik");
            ans.add(word);
            word = new Word();
            word.setName("gate");
            word.setRussian("Ворота");
            word.setUzbek("Darvoza");
            ans.add(word);
            word = new Word();
            word.setName("carpet");
            word.setRussian("Ковер");
            word.setUzbek("Gilam");
            ans.add(word);
            word = new Word();
            word.setName("fridge");
            word.setRussian("Холодильник");
            word.setUzbek("Sovutgich");
            ans.add(word);
            word = new Word();
            word.setName("washing_machine");
            word.setRussian("Стиральная машина");
            word.setUzbek("Kir yuvish mashinasi");
            ans.add(word);
        }
        return ans;


    }
}
